# Generated by Django 4.2.3 on 2023-07-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='messageus',
        ),
    ]
